import { useSelector, useDispatch } from "react-redux";

import {
    increment,
    decrement,
    incrementByAmount,
    reset,
} from "./counterSlice.js";

function Counter() {
    // "Give me the count value from the Redux store.";
    const count = useSelector((state) => state.counter.count);

    // gives us Redux's dispatch function.
    const dispatch = useDispatch();

    return (
        <div>
            <h1>Count: {count}</h1>
            {/* Then: dispatch(increment()); dispatches the action generated by: increment()
            Two step operations:
            First: increment() creates:
                {
                    type: "counter/increment"
                }
            Then: dispatch(...) sends that action to Redux.
            */}
            <button onClick={() => dispatch(increment())}>Increment</button>
            {/* Then: dispatch(increment()); dispatches the action generated by: decrement() */}
            <button onClick={() => dispatch(decrement())}>Decrement</button>
            {/* payload is the data you send along with an action. */}
            <button onClick={() => dispatch(incrementByAmount(6))}>
                Increment by 6
            </button>
            <button onClick={() => dispatch(reset())}>Reset</button>
        </div>
    );
}

export default Counter;
